---
version: '3.9'
services:
  postgres:
    image: postgres:15
    command:
      - postgres
      - '-c'
      - 'config_file=/host/config/postgresql.conf'
    environment:
      POSTGRES_PASSWORD: pg_cpu_test
      POSTGRES_HOST_AUTH_METHOD: cert
    ports:
    - "5432:5432"
    volumes:
    - ./:/host
    - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
  chainsmith:
    image: chainsmith
    volumes:
    - ./:/host
    environment:
      CHAINSMITH_CONFIG: /host/config/chainsmith.yml
