---
version: '3.9'
services:
  postgres:
    image: postgres:15
    command:
      - postgres
      - '-c'
      - 'config_file=/host/config/postgresql.conf'
    environment:
      POSTGRES_PASSWORD: pg_tps_optimizer
      POSTGRES_HOST_AUTH_METHOD: cert
    ports:
    - "5432:5432"
    volumes:
    - ./:/host
    - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
  chainsmith:
    image: mannemsolutions/chainsmith
    volumes:
    - ./:/host
    environment:
      CHAINSMITH_CONFIG: /host/config/chainsmith.yml
  pg_tps_optimizer:
    build: .
    volumes:
    - ./:/host
    environment:
      PGUSER: postgres
      PGHOST: postgres
      PGSSLCERT: /host/config/tls/int_client/certs/postgres.pem
      PGSSLKEY: /host/config/tls/int_client/private/postgres.key.pem
      PGSSLROOTCERT: /host/config/tls/int_server/certs/ca-chain-bundle.cert.pem
      PGTPSRANGE: '1:100'
