---
subject:
  C:  NL
  ST: Zuid Holland
  L:  Alphen aan den Rijn
  O:  Mannem Solutions
  OU: postgres-ssl
  CN: chainsmith

tmpdir: /host/config

intermediates:
  - name: server
    servers:
      localhost:
        - 127.0.0.1
    keyUsages:
      - keyEncipherment
      - dataEncipherment
      - digitalSignature
    extendedKeyUsages:
      - serverAuth
  - name: client
    clients:
      - postgres
    keyUsages:
      - keyEncipherment
      - dataEncipherment
      - digitalSignature
    extendedKeyUsages:
      - clientAuth
